import { RoleName } from './types';

export const PERMISSIONS = {
  TENANT_ADMIN: 'tenant:admin',
  STRATEGY_READ: 'strategy:read',
  STRATEGY_WRITE: 'strategy:write',
  PROJECTS_READ: 'projects:read',
  PROJECTS_WRITE: 'projects:write',
  TALENT_READ: 'talent:read',
  TALENT_WRITE: 'talent:write',
  CV_UPLOAD_SELF: 'cv:upload:self',
  CV_UPLOAD_OTHERS: 'cv:upload:others',
  MARKETPLACE: 'marketplace:use',
  BONUS_CONFIG: 'bonus:config',
  BONUS_VIEW_ALL: 'bonus:view:all',
  DECISIONS_APPROVE: 'decisions:approve',
  INTEGRATIONS_MANAGE: 'integrations:manage',
  SSO_CONFIG: 'sso:config',
  AI_FULL: 'ai:full',
  AUDIT_READ: 'audit:read',
  GDPR_EXPORT: 'gdpr:export',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

const ALL = Object.values(PERMISSIONS);

export const ROLE_PERMISSIONS: Record<RoleName, Permission[]> = {
  [RoleName.SUPER_ADMIN]: ALL,
  [RoleName.CEO]: [
    PERMISSIONS.STRATEGY_READ,
    PERMISSIONS.STRATEGY_WRITE,
    PERMISSIONS.PROJECTS_READ,
    PERMISSIONS.PROJECTS_WRITE,
    PERMISSIONS.TALENT_READ,
    PERMISSIONS.CV_UPLOAD_SELF,
    PERMISSIONS.MARKETPLACE,
    PERMISSIONS.BONUS_VIEW_ALL,
    PERMISSIONS.DECISIONS_APPROVE,
    PERMISSIONS.INTEGRATIONS_MANAGE,
    PERMISSIONS.CV_UPLOAD_OTHERS,
    PERMISSIONS.TALENT_WRITE,
    PERMISSIONS.AI_FULL,
    PERMISSIONS.AUDIT_READ,
  ],
  [RoleName.EXECUTIVE]: [
    PERMISSIONS.STRATEGY_READ,
    PERMISSIONS.STRATEGY_WRITE,
    PERMISSIONS.PROJECTS_READ,
    PERMISSIONS.PROJECTS_WRITE,
    PERMISSIONS.TALENT_READ,
    PERMISSIONS.CV_UPLOAD_SELF,
    PERMISSIONS.MARKETPLACE,
    PERMISSIONS.BONUS_VIEW_ALL,
    PERMISSIONS.DECISIONS_APPROVE,
    PERMISSIONS.AI_FULL,
  ],
  [RoleName.HR]: [
    PERMISSIONS.STRATEGY_READ,
    PERMISSIONS.TALENT_READ,
    PERMISSIONS.TALENT_WRITE,
    PERMISSIONS.CV_UPLOAD_SELF,
    PERMISSIONS.CV_UPLOAD_OTHERS,
    PERMISSIONS.MARKETPLACE,
    PERMISSIONS.BONUS_CONFIG,
    PERMISSIONS.BONUS_VIEW_ALL,
    PERMISSIONS.AI_FULL,
    PERMISSIONS.GDPR_EXPORT,
  ],
  [RoleName.TEAM_LEAD]: [
    PERMISSIONS.STRATEGY_READ,
    PERMISSIONS.PROJECTS_READ,
    PERMISSIONS.PROJECTS_WRITE,
    PERMISSIONS.TALENT_READ,
    PERMISSIONS.CV_UPLOAD_SELF,
    PERMISSIONS.MARKETPLACE,
    PERMISSIONS.AI_FULL,
  ],
  [RoleName.EMPLOYEE]: [
    PERMISSIONS.STRATEGY_READ,
    PERMISSIONS.PROJECTS_READ,
    PERMISSIONS.TALENT_READ,
    PERMISSIONS.CV_UPLOAD_SELF,
    PERMISSIONS.MARKETPLACE,
    PERMISSIONS.AI_FULL,
  ],
};

export function hasPermission(roles: RoleName[], permission: Permission): boolean {
  return roles.some((role) => ROLE_PERMISSIONS[role]?.includes(permission));
}
